### ISSUE TITLE
Setup & Usage

### ISSUE THREAD

**Issue by officialasit** [crypto-trading-master/FlashLoanBSC#1]
Hi @crypto-trading-master ,
I would like to try out this application. Is it just npm i to install the dependencies. It would be great if you would add a setup guide in the Readme.md file.

Thanks

**Comment by crypto-trading-master** [comment]
Hi @officialasit,

npm i should be fine.
This is not for productive puposes. Just code from a course. I also could not retrieve data from Sushiswap.
If you could help, let me know.

**Comment by crypto-trading-master** [comment]
Closed
