### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by Kei-OHKAWA** [crypto-trading-master/FlashLoanBSC#2]
Hi

I would like to use it
Please tell me how to use it.

Where do you set the wallet address etc.?
What do I need to change?

What do you need to install?
How do you start it?

Please.

**Comment by crypto-trading-master** [comment]
@Kei-OHKAWA 
This was just a try from a webcast. It's not working and not further developed.

**Comment by Kei-OHKAWA** [comment]
thank you for your answer. OK.

2022年1月20日(木) 15:34 crypto-trading-master ***@***.***>:
